### ISSUE TITLE
依赖引入失败

### ISSUE THREAD

**Issue by Hunlongyu** [pipipi-pikachu/v-contextmenu-directive#1]
我用 yarn 安装了依赖包, 并且 package.json 显示 版本为 2.0.0

在 `main.js` 引用时, vscode 提示依赖没有安装

![image](https://user-images.githubusercontent.com/15273630/109839287-ee906d00-7c81-11eb-88ae-829ed2142415.png)

**Comment by Hunlongyu** [comment]
我进去看了一下,  package显示入口文件为  `./dist/v-contextmenu-directive.umd.min.js`

但是 `dist` 目录下并没有 这个文件. 你构建配置错了.

**Comment by pipipi-pikachu** [comment]
非常抱歉，更新版本时忘记重新构建了，已修正
